version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
      - 443:443
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
  # openldap:
  #     container_name: openldap
  #     image: osixia/openldap
  #     ports:
  #       - 390:389
  #       - 636:636
  #     environment:
  #       - LDAP_DOMAIN=sec4you.local
  #       - LDAP_ADMIN_PASSWORD=admin
  #       - LDAP_ORGANISATION=sec4you.local
  #     volumes:
  #       - ./data/openldap/slapd/config:/etc/ldap/slapd.d
  #       - ./data/openldap/slapd/database:/var/lib/ldap